#!/usr/bin/env bash

params=$@;
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";

if [ -a 'htdocs/app/etc/env.php' ] || [ -a 'app/etc/env.php' ]
then
    echo "Found Magento 2. Running n98-magerun2";
    if [ -a "$scriptDir/n98-magerun2.phar" ]
    then
        eval "$scriptDir/n98-magerun2.phar $params";
    else
        echo "n98-magerun2.phar not found in $scriptDir";
    fi
elif [ -a 'htdocs/app/etc/config.xml' ] || [ -a 'app/etc/config.xml' ]
then
    echo "Found Magento 1. Running n98-magerun";
    if [ -a "$scriptDir/n98-magerun.phar" ]
    then
        eval "$scriptDir/n98-magerun.phar $params";
    else
        echo "n98-magerun.phar not found in $scriptDir";
    fi
else
    echo "Cannot determine Magento version";
fi
